name: DevOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Build application
        run: |
          echo "Building application..."
          mkdir build
          cp app.txt build/
          echo "Build completed"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Test application
        run: |
          echo "Testing application..."
          grep "DevOps" app.txt
          echo "Test successful"

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t ghcr.io/${{ github.repository_owner }}/devops-app:1.0 .
          echo "Docker image built successfully"

      - name: Check Docker image
        run: docker images

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/devops-app:1.0
          echo "Docker image pushed successfully"
